// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjMxVbIU3tJ8MjSoKC5Y_GmO608CzpZAM',
    appId: '1:258545219689:web:71db857402181195d00af8',
    messagingSenderId: '258545219689',
    projectId: 'absensi-apps-20725',
    authDomain: 'absensi-apps-20725.firebaseapp.com',
    storageBucket: 'absensi-apps-20725.appspot.com',
    measurementId: 'G-3XEYMR1STW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvprDhsHYe9TH2RCYkbvi_i8vqrbu0zkQ',
    appId: '1:258545219689:android:fd81e482437da934d00af8',
    messagingSenderId: '258545219689',
    projectId: 'absensi-apps-20725',
    storageBucket: 'absensi-apps-20725.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjMxVbIU3tJ8MjSoKC5Y_GmO608CzpZAM',
    appId: '1:258545219689:web:21ccd37d7c42a39ed00af8',
    messagingSenderId: '258545219689',
    projectId: 'absensi-apps-20725',
    authDomain: 'absensi-apps-20725.firebaseapp.com',
    storageBucket: 'absensi-apps-20725.appspot.com',
    measurementId: 'G-MT8S7XLCJM',
  );
}
